---
title: "R Notebook"
output: html_notebook
---

## The Crude Survival Estimate

The crude estimate of the SAB (or PTD) rate is the proportion of subjects that experienced the event during the study.  For example, if $n = 10$ and two SAB's were observed, then the crude SAB rate is $2/10 = 0.8$ or 80%.  However, women who experienced SAB at an early time may never enter the study, and enrolled subjects may be lossed to follow-up before the event can be observed.  In other words, the sample may be biased due to left truncation and right censoring.  This is the reason for using survival methods instead of the crude rate.  The KM and FH estimates of the SAB rate are $1 - \hat{S}_{KM}(20)$ and $1 - \hat{S}_{FH}(20)$.  How do they compare to the crude rate?

### KM vs Crude

Suppose $K$ events are observed at times $t_1, t_2, \ldots, t_K$ among $n$ subjects.  The crude SAB rate is $K/n$.  Assuming there are no tied event times, we have $d_i = 1$ for all events, and the SAB rate estimated by the KM method is:
\begin{align}
R_{KM} &:= 1 - \hat{S}_{KM}(20) \\
&= 1 - \prod_{i = 1}^K 1 - \frac{1}{r_i} \\
\end{align}
We see that the SAB rate is determined by the number of subjects $r_i$ at risk at the event times.  This rate will be minimized when the terms in the product are as large as possible, i.e.\ when the $r_i$ are as large as possible.  Specifically, this occurs when $r_1 = n, r_2 = n - 1, \ldots, r_K = n - K + 1$; therefore we have:
\begin{align}
R_{KM} &\geq 1 - \prod_{i = 1}^K 1 - \frac{1}{n-i+1} \\
&= 1 - \prod_{i = 1}^K \frac{n-i}{n-i+1} \\
&= 1 - \left( \frac{n-1}{n} \right) \left( \frac{n-2}{n-1} \right) \cdots \left( \frac{n-K}{n-K-1} \right) \\
&= 1 - \frac{n-K}{n} \\
&= \frac{K}{n}. \\
\end{align}

Therefore, $R_{KM} \geq R_{crude}$, i.e.\ **the KM-based SAB rate is always greater than or equal to the crude rate.**
\emph{cows}